only_rules:
- anyobject_protocol
- block_based_kvo
- class_delegate_protocol
- closure_body_length
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- custom_rules
- cyclomatic_complexity
- deployment_target
- discouraged_assert
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- expiring_todo
- fatal_error_message
- file_length
- file_name_no_space
- first_where
- for_where
- force_try
- function_body_length
- function_parameter_count
- generic_type_name
- identical_operands
- implicit_getter
- implicit_return
- inert_defer
- is_disjoint
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- no_extension_access_modifier
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- operator_whitespace
- operator_usage_whitespace
- optional_enum_case_matching
- orphaned_doc_comment
- overridden_super_call
- override_in_extension
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_interface_builder
- prohibited_super_call
- protocol_property_accessors_order
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- statement_position
- strong_iboutlet
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unneeded_break_in_switch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- vertical_whitespace_closing_braces
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message
- yoda_condition
excluded:
  - .build/
  - Submodules/
  - Carthage/
  - vendor/bundle
  - Blockchain/JavaScript/
  - Modules/*/.build/
  - Modules/*/*.generated.swift
  - SourcePackages/
  - scripts/*/.build/
file_length:
  warning: 600
  error: 800
line_length:
  ignores_comments: true
  warning: 120
  error: 150
type_body_length:
  warning: 200
  error: 350
closure_body_length:
  warning: 60
  error: 280
deployment_target:
  iOS_deployment_target: 13.0
function_body_length:
  warning: 80
  error: 160
empty_count:
  severity: warning
cyclomatic_complexity:
  warning: 10
  error: 40
no_extension_access_modifier:
  severity: warning
